services:
  drone-srcb:
    build: .
    environment:
      API_ID: 18146532
      API_HASH: 2b8d542b5487e2faf26828a52845b2e1
      BOT_TOKEN: $BOT_TOKEN 
      SESSION: $SESSION
      AUTH: $AUTH
    
    ports:
      - 8080
    resources:
      cpu: 1000m
      memory: 3Gi
